name: pubky-homeserver
region: nyc
services:
- name: pubky-homeserver
  github:
    repo: PastaGringo/pubky-homeserver-docker
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 6286
  instance_count: 1
  instance_size_slug: basic-xxs
  source_dir: /
  envs:
  - key: PUBKY_VERSION
    value: v0.5.4
  - key: PLATFORM
    value: linux-amd64
  - key: PUBKY_HOST
    value: 0.0.0.0
  - key: PUBKY_PORT
    value: "6287"
  - key: PUBKY_DATA_DIR
    value: /app/data
  - key: RUST_LOG
    value: info